# Generated by Django 4.1.3 on 2023-01-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Dept', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=20)),
                ('Mark1', models.IntegerField()),
                ('Mark2', models.IntegerField()),
                ('Mark3', models.IntegerField()),
                ('Mark4', models.IntegerField()),
            ],
        ),
    ]
