# Generated by Django 4.2.6 on 2023-12-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_studata1_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studata1',
            old_name='Dept',
            new_name='Student_Dept',
        ),
        migrations.RenameField(
            model_name='studata1',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Student',
            new_name='Student_Name',
        ),
    ]
